#include "wasm/WasmTierUpCount.cpp"
#include "wasm/WasmValidate.cpp"
#include "wasm/WasmWorklist.cpp"
#include "wasm/js/JSToWasm.cpp"
#include "wasm/js/JSToWasmICCallee.cpp"
#include "wasm/js/JSWebAssembly.cpp"
#include "wasm/js/JSWebAssemblyCodeBlock.cpp"
#include "wasm/js/JSWebAssemblyCodeBlockHeapCellType.cpp"
